import { PrismaClient } from "@prisma/client";

const prisma = new PrismaClient();

async function main() {
  // Criar os planos
  const plans = [
    {
      name: "Light",
      description: "Plano Light - Acesso básico",
      features: [
        "Busca de vagas",
        "Alertas por e-mail",
        "Salvar vagas favoritas",
      ],
      price: 15.0,
      interval: "week",
      billingCycle: "weekly",
      stripePriceId: "price_1QZIUyKs3g6lFwB4y4N13cOU",
      active: true,
    },
    {
      name: "Gold",
      description: "Plano Gold - Acesso completo",
      features: [
        "Todas as funcionalidades do plano Light",
        "Alertas por WhatsApp",
        "Análise de compatibilidade com vagas",
        "Prioridade nas buscas",
      ],
      price: 30.0,
      interval: "month",
      billingCycle: "monthly",
      stripePriceId: "price_1QZIUyKs3g6lFwB4y4N13cOU",
      active: true,
    },
  ];

  // Limpar a tabela de planos antes de inserir
  await prisma.plan.deleteMany();

  // Inserir os planos
  for (const plan of plans) {
    await prisma.plan.create({
      data: plan,
    });
  }

  // Inserir áreas de trabalho e profissões populares
  const jobAreas = [
    { name: "Engenheiro Civil" },
    { name: "Engenheiro Mecânico" },
    { name: "Engenheiro Elétrico" },
    { name: "Engenheiro de Produção" },
    { name: "Engenheiro Ambiental" },
    { name: "Engenheiro Químico" },
    { name: "Engenheiro de Software" },
    { name: "Engenheiro de Dados" },
    { name: "Desenvolvedor Web" },
    { name: "Desenvolvedor Mobile" },
    { name: "Cientista de Dados" },
    { name: "Administrador de Redes" },
    { name: "Analista de Segurança da Informação" },
    { name: "Analista de Sistemas" },
    { name: "Administrador de Empresas" },
    { name: "Gerente Administrativo" },
    { name: "Secretária Executiva" },
    { name: "Consultor de Vendas" },
    { name: "Gerente de Vendas" },
    { name: "Representante Comercial" },
    { name: "Especialista em SEO" },
    { name: "Social Media" },
    { name: "Redator de Conteúdo" },
    { name: "Gerente de Marketing" },
    { name: "Analista Financeiro" },
    { name: "Contador" },
    { name: "Gerente Financeiro" },
    { name: "Designer Gráfico" },
    { name: "UX/UI Designer" },
    { name: "Ilustrador" },
    { name: "Motion Designer" },
    { name: "Professor de Matemática" },
    { name: "Professor de Inglês" },
    { name: "Pedagogo" },
    { name: "Médico Clínico Geral" },
    { name: "Enfermeiro" },
    { name: "Fisioterapeuta" },
    { name: "Psicólogo" },
    { name: "Nutricionista" },
    { name: "Arquiteto Urbanista" },
    { name: "Designer de Interiores" },
    { name: "Pedreiro" },
    { name: "Mestre de Obras" },
    { name: "Carpinteiro" },
    { name: "Motorista" },
    { name: "Piloto de Avião" },
    { name: "Comissário de Bordo" },
    { name: "Chef de Cozinha" },
    { name: "Padeiro" },
    { name: "Confeiteiro" },
    { name: "Músico" },
    { name: "Ator" },
    { name: "Pintor Artístico" },
    { name: "Escultor" },
    { name: "Advogado" },
    { name: "Procurador" },
    { name: "Juiz" },
    { name: "Escrivão" },
    { name: "Policial" },
    { name: "Bombeiro" },
    { name: "Militar" },
    { name: "Agente de Trânsito" },
    { name: "Técnico em Enfermagem" },
    { name: "Farmacêutico" },
    { name: "Veterinário" },
    { name: "Zootecnista" },
    { name: "Biólogo" },
    { name: "Geólogo" },
    { name: "Meteorologista" },
    { name: "Agrônomo" },
    { name: "Oceanógrafo" },
    { name: "Engenheiro Naval" },
    { name: "Engenheiro Aeroespacial" },
    { name: "Técnico em Informática" },
    { name: "Analista de Dados" },
    { name: "Gestor de Projetos" },
    { name: "Consultor Financeiro" },
    { name: "Técnico em Eletrônica" },
    { name: "Técnico em Mecânica" },
    { name: "Eletricista" },
    { name: "Soldador" },
    { name: "Operador de Máquinas" },
    { name: "Garçom" },
    { name: "Bartender" },
    { name: "Recepcionista" },
    { name: "Agente de Viagens" },
    { name: "Turismólogo" },
    { name: "Guia de Turismo" },
    { name: "Tradutor" },
    { name: "Intérprete de Libras" },
    { name: "Psicanalista" },
    { name: "Técnico em Radiologia" },
    { name: "Esteticista" },
    { name: "Maquiador" },
    { name: "Cabeleireiro" },
    { name: "Barbeiro" },
    { name: "Manicure" },
    { name: "Costureiro" },
    { name: "Estilista" },
    { name: "Jornalista" },
    { name: "Fotógrafo" },
    { name: "Videomaker" },
    { name: "Youtuber" },
    { name: "Engenheiro Agrícola" },
    { name: "Engenheiro Florestal" },
    { name: "Engenheiro de Controle e Automação" },
    { name: "Engenheiro de Petróleo" },
    { name: "Engenheiro de Minas" },
    { name: "Técnico em Agrimensura" },
    { name: "Topógrafo" },
    { name: "Geógrafo" },
    { name: "Astrônomo" },
    { name: "Físico" },
    { name: "Químico" },
    { name: "Técnico em Química" },
    { name: "Engenheiro de Materiais" },
    { name: "Técnico em Meio Ambiente" },
    { name: "Gestor Ambiental" },
    { name: "Ecologista" },
    { name: "Técnico em Alimentos" },
    { name: "Engenheiro de Alimentos" },
    { name: "Zootecnista" },
    { name: "Agricultor" },
    { name: "Apicultor" },
    { name: "Pesquisador Científico" },
    { name: "Técnico de Laboratório" },
    { name: "Biomédico" },
    { name: "Analista Clínico" },
    { name: "Geneticista" },
    { name: "Microbiologista" },
    { name: "Técnico em Biotecnologia" },
    { name: "Técnico em Nutrição" },
    { name: "Fonoaudiólogo" },
    { name: "Oftalmologista" },
    { name: "Dermatologista" },
    { name: "Psiquiatra" },
    { name: "Ortopedista" },
    { name: "Cardiologista" },
    { name: "Cirurgião Geral" },
    { name: "Cirurgião Plástico" },
    { name: "Ginecologista" },
    { name: "Pediatra" },
    { name: "Veterinário de Animais Silvestres" },
    { name: "Técnico em Zootecnia" },
    { name: "Oceanógrafo" },
    { name: "Engenheiro Sanitarista" },
    { name: "Advogado Trabalhista" },
    { name: "Advogado Criminalista" },
    { name: "Advogado Tributarista" },
    { name: "Advogado Imobiliário" },
    { name: "Advogado Ambientalista" },
    { name: "Promotor de Justiça" },
    { name: "Defensor Público" },
    { name: "Delegado de Polícia" },
    { name: "Investigador" },
    { name: "Perito Criminal" },
    { name: "Analista Legislativo" },
    { name: "Diplomata" },
    { name: "Historiador" },
    { name: "Antropólogo" },
    { name: "Sociólogo" },
    { name: "Psicopedagogo" },
    { name: "Arqueólogo" },
    { name: "Assistente Social" },
    { name: "Gestor de Recursos Humanos" },
    { name: "Gerente de Projetos" },
    { name: "Coach" },
    { name: "Analista de Crédito" },
    { name: "Analista de Investimentos" },
    { name: "Corretor de Imóveis" },
    { name: "Corretor de Seguros" },
    { name: "Gestor de Logística" },
    { name: "Operador de Empilhadeira" },
    { name: "Despachante Aduaneiro" },
    { name: "Engenheiro de Transportes" },
    { name: "Maquinista" },
    { name: "Comandante de Navio" },
    { name: "Tecnólogo em Gestão Pública" },
    { name: "Analista de Comércio Exterior" },
    { name: "Economista" },
    { name: "Estatístico" },
    { name: "Atuário" },
    { name: "Perito Contábil" },
    { name: "Administrador Hospitalar" },
    { name: "Técnico em Prótese Dentária" },
    { name: "Técnico em Saúde Bucal" },
    { name: "Cirurgião Dentista" },
    { name: "Ortodontista" },
    { name: "Periodontista" },
    { name: "Radiologista" },
    { name: "Técnico em Radiologia" },
    { name: "Técnico em Segurança do Trabalho" },
    { name: "Engenheiro de Segurança do Trabalho" },
    { name: "Auditor Fiscal" },
    { name: "Agente de Saúde Pública" },
    { name: "Instrutor de Trânsito" },
    { name: "Educador Social" },
    { name: "Mestre Cervejeiro" },
    { name: "Sommelier" },
    { name: "Barista" },
    { name: "Pizzaiolo" },
    { name: "Marceneiro" },
    { name: "Serralheiro" },
    { name: "Tatuador" },
    { name: "Body Piercer" },
  ];

  // Limpar a tabela antes de inserir
  await prisma.jobArea.deleteMany();

  // Inserir todas as áreas de uma vez
  await prisma.jobArea.createMany({
    data: jobAreas,
    skipDuplicates: true,
  });
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
